apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
resources:
  - ../../base
images:
  # This entry will be edited by CI with `kustomize edit set image app=<ECR>:<SHA>`
  - name: app
    newName: app
    newTag: latest
