apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
resources:
  - ../../base
images:
  - name: app
    newName: 630398150656.dkr.ecr.ap-south-1.amazonaws.com/hello-eks
    newTag: latest
