name: CI/CD – Build, Scan, Deploy to EKS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: hello-eks
  ECR_REPO: 630398150656.dkr.ecr.ap-south-1.amazonaws.com/hello-eks

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::630398150656:role/hello-eks-gha-role

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push (tagged with SHA and latest)
        env:
          IMAGE_SHA: ${{ env.ECR_REPO }}:${{ github.sha }}
          IMAGE_LATEST: ${{ env.ECR_REPO }}:latest
        run: |
          set -euo pipefail
          # --- Detect Dockerfile location (subfolder support) ---
          DF=""
          CTX=""
          if [ -f ./app/Dockerfile ]; then
            DF=./app/Dockerfile
            CTX=./app
          elif [ -f ./Dockerfile ]; then
            DF=./Dockerfile
            CTX=.
          else
            DF=$(find . -maxdepth 3 -name Dockerfile | head -n1 || true)
            if [ -z "$DF" ]; then
              echo "ERROR: Dockerfile not found in repo (searched to depth 3)."
              exit 1
            fi
            CTX=$(dirname "$DF")
          fi
          echo "Using Dockerfile: $DF"
          echo "Build context:   $CTX"
          docker build -f "$DF" -t "$IMAGE_SHA" -t "$IMAGE_LATEST" "$CTX"
          docker push "$IMAGE_SHA"
          docker push "$IMAGE_LATEST"

      - name: Trivy scan (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: image
          image-ref: ${{ env.ECR_REPO }}:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

- name: Install Kustomize (official script)
  run: |
    set -euo pipefail
    VER="v5.4.3"
    curl -fsSL https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh -o /tmp/install_kustomize.sh
    bash /tmp/install_kustomize.sh ${VER}
    sudo mv kustomize /usr/local/bin/
    kustomize version
